// <copyright file="MainForm.Designer.cs" company="PublicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace TitleChangerLauncherGenerator
{
    partial class MainForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
        	System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
        	this.mainStatusStrip = new System.Windows.Forms.StatusStrip();
        	this.mainToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
        	this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.newToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
        	this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.headquartersPatreoncomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.sourceCodeGithubcomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.threadDonationCodercomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator5 = new System.Windows.Forms.ToolStripSeparator();
        	this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.mainTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
        	this.browseButton = new System.Windows.Forms.Button();
        	this.programLabel = new System.Windows.Forms.Label();
        	this.previousTitleLabel = new System.Windows.Forms.Label();
        	this.newTitleLabel = new System.Windows.Forms.Label();
        	this.previousTitleTextBox = new System.Windows.Forms.TextBox();
        	this.newTiTLeTextBox = new System.Windows.Forms.TextBox();
        	this.generateLauncherTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
        	this.generateRevertButton = new System.Windows.Forms.Button();
        	this.radioTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
        	this.generateRadioButton = new System.Windows.Forms.RadioButton();
        	this.revertRadioButton = new System.Windows.Forms.RadioButton();
        	this.inPlaceCheckBox = new System.Windows.Forms.CheckBox();
        	this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
        	this.mainStatusStrip.SuspendLayout();
        	this.mainMenuStrip.SuspendLayout();
        	this.mainTableLayoutPanel.SuspendLayout();
        	this.generateLauncherTableLayoutPanel.SuspendLayout();
        	this.radioTableLayoutPanel.SuspendLayout();
        	this.SuspendLayout();
        	// 
        	// mainStatusStrip
        	// 
        	this.mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.mainToolStripStatusLabel});
        	this.mainStatusStrip.Location = new System.Drawing.Point(0, 164);
        	this.mainStatusStrip.Name = "mainStatusStrip";
        	this.mainStatusStrip.Size = new System.Drawing.Size(308, 22);
        	this.mainStatusStrip.TabIndex = 0;
        	this.mainStatusStrip.Text = "statusStrip1";
        	// 
        	// mainToolStripStatusLabel
        	// 
        	this.mainToolStripStatusLabel.Name = "mainToolStripStatusLabel";
        	this.mainToolStripStatusLabel.Size = new System.Drawing.Size(261, 17);
        	this.mainToolStripStatusLabel.Text = "1) Set target, previous and new title. 2) Generate!";
        	// 
        	// mainMenuStrip
        	// 
        	this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.fileToolStripMenuItem,
        	        	        	this.helpToolStripMenuItem});
        	this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
        	this.mainMenuStrip.Name = "mainMenuStrip";
        	this.mainMenuStrip.Size = new System.Drawing.Size(308, 24);
        	this.mainMenuStrip.TabIndex = 1;
        	this.mainMenuStrip.Text = "menuStrip1";
        	// 
        	// fileToolStripMenuItem
        	// 
        	this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.newToolStripMenuItem,
        	        	        	this.toolStripSeparator2,
        	        	        	this.exitToolStripMenuItem});
        	this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
        	this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
        	this.fileToolStripMenuItem.Text = "&File";
        	// 
        	// newToolStripMenuItem
        	// 
        	this.newToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("newToolStripMenuItem.Image")));
        	this.newToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.newToolStripMenuItem.Name = "newToolStripMenuItem";
        	this.newToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
        	this.newToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
        	this.newToolStripMenuItem.Text = "&New";
        	this.newToolStripMenuItem.Click += new System.EventHandler(this.OnNewToolStripMenuItemClick);
        	// 
        	// toolStripSeparator2
        	// 
        	this.toolStripSeparator2.Name = "toolStripSeparator2";
        	this.toolStripSeparator2.Size = new System.Drawing.Size(138, 6);
        	// 
        	// exitToolStripMenuItem
        	// 
        	this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
        	this.exitToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
        	this.exitToolStripMenuItem.Text = "E&xit";
        	this.exitToolStripMenuItem.Click += new System.EventHandler(this.OnExitToolStripMenuItemClick);
        	// 
        	// helpToolStripMenuItem
        	// 
        	this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.headquartersPatreoncomToolStripMenuItem,
        	        	        	this.sourceCodeGithubcomToolStripMenuItem,
        	        	        	this.threadDonationCodercomToolStripMenuItem,
        	        	        	this.toolStripSeparator5,
        	        	        	this.aboutToolStripMenuItem});
        	this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
        	this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
        	this.helpToolStripMenuItem.Text = "&Help";
        	// 
        	// headquartersPatreoncomToolStripMenuItem
        	// 
        	this.headquartersPatreoncomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("headquartersPatreoncomToolStripMenuItem.Image")));
        	this.headquartersPatreoncomToolStripMenuItem.Name = "headquartersPatreoncomToolStripMenuItem";
        	this.headquartersPatreoncomToolStripMenuItem.Size = new System.Drawing.Size(236, 22);
        	this.headquartersPatreoncomToolStripMenuItem.Text = "&Headquarters @ Patreon.com";
        	this.headquartersPatreoncomToolStripMenuItem.Click += new System.EventHandler(this.OnHeadquartersPatreoncomToolStripMenuItemClick);
        	// 
        	// sourceCodeGithubcomToolStripMenuItem
        	// 
        	this.sourceCodeGithubcomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("sourceCodeGithubcomToolStripMenuItem.Image")));
        	this.sourceCodeGithubcomToolStripMenuItem.Name = "sourceCodeGithubcomToolStripMenuItem";
        	this.sourceCodeGithubcomToolStripMenuItem.Size = new System.Drawing.Size(236, 22);
        	this.sourceCodeGithubcomToolStripMenuItem.Text = "&Source code @ Github.com";
        	this.sourceCodeGithubcomToolStripMenuItem.Click += new System.EventHandler(this.OnSourceCodeGithubcomToolStripMenuItemClick);
        	// 
        	// threadDonationCodercomToolStripMenuItem
        	// 
        	this.threadDonationCodercomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("threadDonationCodercomToolStripMenuItem.Image")));
        	this.threadDonationCodercomToolStripMenuItem.Name = "threadDonationCodercomToolStripMenuItem";
        	this.threadDonationCodercomToolStripMenuItem.Size = new System.Drawing.Size(236, 22);
        	this.threadDonationCodercomToolStripMenuItem.Text = "Thread @ &DonationCoder.com";
        	this.threadDonationCodercomToolStripMenuItem.Click += new System.EventHandler(this.OnThreadDonationCodercomToolStripMenuItemClick);
        	// 
        	// toolStripSeparator5
        	// 
        	this.toolStripSeparator5.Name = "toolStripSeparator5";
        	this.toolStripSeparator5.Size = new System.Drawing.Size(233, 6);
        	// 
        	// aboutToolStripMenuItem
        	// 
        	this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
        	this.aboutToolStripMenuItem.Size = new System.Drawing.Size(236, 22);
        	this.aboutToolStripMenuItem.Text = "&About...";
        	this.aboutToolStripMenuItem.Click += new System.EventHandler(this.OnAboutToolStripMenuItemClick);
        	// 
        	// mainTableLayoutPanel
        	// 
        	this.mainTableLayoutPanel.ColumnCount = 2;
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 41.23376F));
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 58.76624F));
        	this.mainTableLayoutPanel.Controls.Add(this.browseButton, 1, 0);
        	this.mainTableLayoutPanel.Controls.Add(this.programLabel, 0, 0);
        	this.mainTableLayoutPanel.Controls.Add(this.previousTitleLabel, 0, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.newTitleLabel, 0, 2);
        	this.mainTableLayoutPanel.Controls.Add(this.previousTitleTextBox, 1, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.newTiTLeTextBox, 1, 2);
        	this.mainTableLayoutPanel.Controls.Add(this.generateLauncherTableLayoutPanel, 0, 3);
        	this.mainTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.mainTableLayoutPanel.Location = new System.Drawing.Point(0, 24);
        	this.mainTableLayoutPanel.Name = "mainTableLayoutPanel";
        	this.mainTableLayoutPanel.RowCount = 5;
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
        	this.mainTableLayoutPanel.Size = new System.Drawing.Size(308, 140);
        	this.mainTableLayoutPanel.TabIndex = 2;
        	// 
        	// browseButton
        	// 
        	this.browseButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.browseButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.browseButton.Location = new System.Drawing.Point(129, 3);
        	this.browseButton.Name = "browseButton";
        	this.browseButton.Size = new System.Drawing.Size(176, 22);
        	this.browseButton.TabIndex = 0;
        	this.browseButton.Text = "Browse for target";
        	this.browseButton.UseVisualStyleBackColor = true;
        	this.browseButton.Click += new System.EventHandler(this.OnBrowseButtonClick);
        	// 
        	// programLabel
        	// 
        	this.programLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.programLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.programLabel.Location = new System.Drawing.Point(3, 0);
        	this.programLabel.Name = "programLabel";
        	this.programLabel.Size = new System.Drawing.Size(120, 28);
        	this.programLabel.TabIndex = 1;
        	this.programLabel.Text = "Program:";
        	this.programLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	// 
        	// previousTitleLabel
        	// 
        	this.previousTitleLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.previousTitleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.previousTitleLabel.Location = new System.Drawing.Point(3, 28);
        	this.previousTitleLabel.Name = "previousTitleLabel";
        	this.previousTitleLabel.Size = new System.Drawing.Size(120, 28);
        	this.previousTitleLabel.TabIndex = 2;
        	this.previousTitleLabel.Text = "Previous title:";
        	this.previousTitleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	// 
        	// newTitleLabel
        	// 
        	this.newTitleLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.newTitleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.newTitleLabel.Location = new System.Drawing.Point(3, 56);
        	this.newTitleLabel.Name = "newTitleLabel";
        	this.newTitleLabel.Size = new System.Drawing.Size(120, 28);
        	this.newTitleLabel.TabIndex = 3;
        	this.newTitleLabel.Text = "New title:";
        	this.newTitleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	// 
        	// previousTitleTextBox
        	// 
        	this.previousTitleTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.previousTitleTextBox.Location = new System.Drawing.Point(129, 31);
        	this.previousTitleTextBox.Name = "previousTitleTextBox";
        	this.previousTitleTextBox.Size = new System.Drawing.Size(176, 20);
        	this.previousTitleTextBox.TabIndex = 4;
        	this.previousTitleTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
        	// 
        	// newTiTLeTextBox
        	// 
        	this.newTiTLeTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.newTiTLeTextBox.Location = new System.Drawing.Point(129, 59);
        	this.newTiTLeTextBox.Name = "newTiTLeTextBox";
        	this.newTiTLeTextBox.Size = new System.Drawing.Size(176, 20);
        	this.newTiTLeTextBox.TabIndex = 5;
        	this.newTiTLeTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
        	// 
        	// generateLauncherTableLayoutPanel
        	// 
        	this.generateLauncherTableLayoutPanel.ColumnCount = 3;
        	this.mainTableLayoutPanel.SetColumnSpan(this.generateLauncherTableLayoutPanel, 2);
        	this.generateLauncherTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
        	this.generateLauncherTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
        	this.generateLauncherTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
        	this.generateLauncherTableLayoutPanel.Controls.Add(this.generateRevertButton, 1, 1);
        	this.generateLauncherTableLayoutPanel.Controls.Add(this.radioTableLayoutPanel, 1, 0);
        	this.generateLauncherTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.generateLauncherTableLayoutPanel.Location = new System.Drawing.Point(0, 84);
        	this.generateLauncherTableLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
        	this.generateLauncherTableLayoutPanel.Name = "generateLauncherTableLayoutPanel";
        	this.generateLauncherTableLayoutPanel.RowCount = 2;
        	this.mainTableLayoutPanel.SetRowSpan(this.generateLauncherTableLayoutPanel, 2);
        	this.generateLauncherTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.generateLauncherTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
        	this.generateLauncherTableLayoutPanel.Size = new System.Drawing.Size(308, 56);
        	this.generateLauncherTableLayoutPanel.TabIndex = 6;
        	// 
        	// generateRevertButton
        	// 
        	this.generateRevertButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.generateRevertButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.generateRevertButton.ForeColor = System.Drawing.Color.Red;
        	this.generateRevertButton.Location = new System.Drawing.Point(49, 23);
        	this.generateRevertButton.Name = "generateRevertButton";
        	this.generateRevertButton.Size = new System.Drawing.Size(209, 30);
        	this.generateRevertButton.TabIndex = 0;
        	this.generateRevertButton.Text = "&Generate in-place Launcher";
        	this.generateRevertButton.UseVisualStyleBackColor = true;
        	this.generateRevertButton.Click += new System.EventHandler(this.OnGenerateRevertButtonClick);
        	// 
        	// radioTableLayoutPanel
        	// 
        	this.radioTableLayoutPanel.ColumnCount = 3;
        	this.radioTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
        	this.radioTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
        	this.radioTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
        	this.radioTableLayoutPanel.Controls.Add(this.generateRadioButton, 0, 0);
        	this.radioTableLayoutPanel.Controls.Add(this.revertRadioButton, 1, 0);
        	this.radioTableLayoutPanel.Controls.Add(this.inPlaceCheckBox, 2, 0);
        	this.radioTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.radioTableLayoutPanel.Location = new System.Drawing.Point(46, 0);
        	this.radioTableLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
        	this.radioTableLayoutPanel.Name = "radioTableLayoutPanel";
        	this.radioTableLayoutPanel.RowCount = 1;
        	this.radioTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
        	this.radioTableLayoutPanel.Size = new System.Drawing.Size(215, 20);
        	this.radioTableLayoutPanel.TabIndex = 1;
        	// 
        	// generateRadioButton
        	// 
        	this.generateRadioButton.Checked = true;
        	this.generateRadioButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.generateRadioButton.Location = new System.Drawing.Point(1, 1);
        	this.generateRadioButton.Margin = new System.Windows.Forms.Padding(1);
        	this.generateRadioButton.Name = "generateRadioButton";
        	this.generateRadioButton.Size = new System.Drawing.Size(69, 18);
        	this.generateRadioButton.TabIndex = 0;
        	this.generateRadioButton.TabStop = true;
        	this.generateRadioButton.Text = "&Generate";
        	this.generateRadioButton.UseVisualStyleBackColor = true;
        	this.generateRadioButton.CheckedChanged += new System.EventHandler(this.OnGenerateRadioButtonCheckedChanged);
        	// 
        	// revertRadioButton
        	// 
        	this.revertRadioButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.revertRadioButton.Location = new System.Drawing.Point(72, 1);
        	this.revertRadioButton.Margin = new System.Windows.Forms.Padding(1);
        	this.revertRadioButton.Name = "revertRadioButton";
        	this.revertRadioButton.Size = new System.Drawing.Size(69, 18);
        	this.revertRadioButton.TabIndex = 1;
        	this.revertRadioButton.Text = "&Revert";
        	this.revertRadioButton.UseVisualStyleBackColor = true;
        	this.revertRadioButton.CheckedChanged += new System.EventHandler(this.OnRevertRadioButtonCheckedChanged);
        	// 
        	// inPlaceCheckBox
        	// 
        	this.inPlaceCheckBox.Checked = true;
        	this.inPlaceCheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
        	this.inPlaceCheckBox.Location = new System.Drawing.Point(143, 1);
        	this.inPlaceCheckBox.Margin = new System.Windows.Forms.Padding(1);
        	this.inPlaceCheckBox.Name = "inPlaceCheckBox";
        	this.inPlaceCheckBox.Size = new System.Drawing.Size(71, 18);
        	this.inPlaceCheckBox.TabIndex = 2;
        	this.inPlaceCheckBox.Text = "In-place";
        	this.inPlaceCheckBox.UseVisualStyleBackColor = true;
        	this.inPlaceCheckBox.CheckedChanged += new System.EventHandler(this.OnInPlaceCheckBoxCheckedChanged);
        	// 
        	// openFileDialog
        	// 
        	this.openFileDialog.DefaultExt = "exe";
        	this.openFileDialog.Filter = "EXE Files (*.exe)|*.exe|All files (*.*)|*.*";
        	this.openFileDialog.Title = "Select target executable file";
        	// 
        	// MainForm
        	// 
        	this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        	this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        	this.ClientSize = new System.Drawing.Size(308, 186);
        	this.Controls.Add(this.mainTableLayoutPanel);
        	this.Controls.Add(this.mainStatusStrip);
        	this.Controls.Add(this.mainMenuStrip);
        	this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
        	this.MainMenuStrip = this.mainMenuStrip;
        	this.Name = "MainForm";
        	this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        	this.Text = "Title Changer Launcher Generator";
        	this.mainStatusStrip.ResumeLayout(false);
        	this.mainStatusStrip.PerformLayout();
        	this.mainMenuStrip.ResumeLayout(false);
        	this.mainMenuStrip.PerformLayout();
        	this.mainTableLayoutPanel.ResumeLayout(false);
        	this.mainTableLayoutPanel.PerformLayout();
        	this.generateLauncherTableLayoutPanel.ResumeLayout(false);
        	this.radioTableLayoutPanel.ResumeLayout(false);
        	this.ResumeLayout(false);
        	this.PerformLayout();
        }
        private System.Windows.Forms.OpenFileDialog openFileDialog;
        private System.Windows.Forms.CheckBox inPlaceCheckBox;
        private System.Windows.Forms.RadioButton revertRadioButton;
        private System.Windows.Forms.RadioButton generateRadioButton;
        private System.Windows.Forms.TableLayoutPanel radioTableLayoutPanel;
        private System.Windows.Forms.ToolStripMenuItem threadDonationCodercomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem sourceCodeGithubcomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem headquartersPatreoncomToolStripMenuItem;
        private System.Windows.Forms.Button generateRevertButton;
        private System.Windows.Forms.TableLayoutPanel generateLauncherTableLayoutPanel;
        private System.Windows.Forms.TextBox newTiTLeTextBox;
        private System.Windows.Forms.TextBox previousTitleTextBox;
        private System.Windows.Forms.Label newTitleLabel;
        private System.Windows.Forms.Label previousTitleLabel;
        private System.Windows.Forms.Label programLabel;
        private System.Windows.Forms.Button browseButton;
        private System.Windows.Forms.TableLayoutPanel mainTableLayoutPanel;
        private System.Windows.Forms.ToolStripStatusLabel mainToolStripStatusLabel;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator5;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem newToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.MenuStrip mainMenuStrip;
        private System.Windows.Forms.StatusStrip mainStatusStrip;
    }
}
